### ISSUE TITLE
Payment_entity.amount не соответствует стоимости заявленной на главной странице.

### ISSUE THREAD

**Issue by FlyingDog265** [FlyingDog265/NetologyDiploma#2]
_Payment_entity.amount_ не соответствует стоимости заявленной на главной странице после оформления заявки

**Шаги:**
1. В браузере перейти по адресу localhost:8080
1. На главной странице в блоке превью тура заявлена стоимость 45 000
1. Кликнуть "Купить"
1. Оформить заявку используя карту с валидными данными:
    * В поле "Номер карты" ввести: 4444 4444 4444 4441
    * В поле "Месяц" ввести: 08
    * В поле "Год" ввести: 22
    * Поле "Владелец" ввести: Ivanov Ivan
    * В поле "CVC/CVV" ввести: 999
    * Нажать кнопку "Продолжить"
1. Дождаться сообщения об успешной операции
1. Перейти в БД

**Ожидаемый результат**
* В таблице _payment_entity_ содержится запись о транзакции
* Столбец _amount_ содержит значение **45000**

**Фактический результат**
* В таблице _payment_entity_ содержится запись о транзакции
* Столбец _amount_ содержит значение **4500000**

**Окружение**
* ОS Windows 10 version 2020 64-bit
* Browser Google Chrome Версия 91.0.4472.164
* openjdk version "11.0.9" 2020-10-20

**Скрины**
![4](https://user-images.githubusercontent.com/44607099/126759598-69c6ce3d-1ffd-4a7f-80b9-96c8f29dc68d.png)
![3](https://user-images.githubusercontent.com/44607099/126759693-82685728-e6fb-45e2-9e27-b7c8243b02af.jpg)

**Comment by ArRomanov** [comment]
На самом деле, в БД значение хранится в копейках. Иногда так делают, чтобы избежать потерь при округлении рублей. Можно сказать, что не баг, а фича)

**Comment by FlyingDog265** [comment]
Спасибо, буду знать)
В таком случае закрываю ишью)
